name: squashfs
version: 0.0.1

description:
  A native Dart implementation of the squashfs filesystem format.

homepage: https://github.com/robert-ancell/squashfs.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
